version: '2'
services:
  api:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://idealize:idealize@postgres:5432/idealize
      NODE_ENV: development
      PORT: 8080
    ports:
      - '8080:8080'
    command: yarn start:dev
    volumes:
      - .:/app/
  postgres:
    image: postgres:11.9
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: idealize
      POSTGRES_PASSWORD: idealize
      POSTGRES_DB: idealize
